config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :tasks
resources :users
resources :labels

root "tasks#index"
get "login" => "users#login_form"
post "login" => "users#login"
post "logout" => "users#logout"

namespace :admin do
  resources :users
end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :task_labels
  has_many :tasks, :through => :task_labels

  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_labels
  has_many :labels, :through => :task_labels

  validates :content, presence: true
  enum status: { NOT:0, WIP:1, DONE:2 }
  enum priority: { Low:0, Mid:1, High:2 }

  def user
    return User.find_by(id: self.user_id)
  end

  def self.search(search)
    if search
        Task.where(["content LIKE(?)", "%#{search}%"])
    else
        Task.all
    end
  end

end

app/models/task_label.rb
class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tasks, dependent: :destroy
  before_destroy :check_admin_users, prepend: true


  def check_admin_users
    if User.where(admin: 'true').count == 1
      errors.add :base, 'this user is last admin'
      throw(:abort)
    end
  end


  validates :name, {presence: true}
  validates :email, {presence: true, uniqueness: true}

  enum admin:{false:0,true:1}

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :auth_user
  before_action :auth_admin

  def auth_admin
    if @current_user.admin != "true"
      flash[:notice] = "You don't have admin authority"
      redirect_to '/'
      return
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :admin)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user

  def auth_user
    if !@current_user
      flash[:notice] = "You don't have authority"
      redirect_to "/login"
      return
    end
  end

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  


end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

  def index
    @labels = Label.all
  end

  def create
    @label = Label.new(params.require(:label).permit(:name))
    @label.save
    redirect_to labels_path
  end

  def destroy
    @label = Label.find(params[:id])
    @label.destroy
    redirect_to labels_path
  end

  def show
    @label = Label.find(params[:id])
    @tasks = @label.tasks.page(params[:page]).per(5)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :auth_user,{only:[:new,:edit,:update,:destroy]}
  before_action :ensure_correct_user,{only:[:edit,:update,:destroy]}


  def ensure_correct_user
    @task = Task.find_by(id: params[:id])
    if @current_user.id != @task.user_id
      flash[:notice] = "You don't have authority"
      redirect_to("/")
    end
  end

  def index
    @tasks = Task.all.order(created_at: :asc).search(params[:search]).page(params[:page]).per(5)
    #@tasks = Task.search(params[:search])
    if params[:sort] == 'updated_at'
      @tasks = Task.order(updated_at: :desc).page(params[:page]).per(5)
    elsif params[:sort] == 'deadline'
      @tasks = Task.order(deadline: :asc).page(params[:page]).per(5)
    elsif params[:sort] == 'status'
      @tasks = Task.order(status: :asc).page(params[:page]).per(5)
    elsif params[:sort] == 'priority'
      @tasks = Task.order(priority: :desc).page(params[:page]).per(5)
    #else
    #  @tasks = Task.page(params[:page]).per(5)
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = @current_user.id
    if @task.save
      redirect_to tasks_path
    else
      render "new"
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render "edit"
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end


  private
    def task_params
      params.require(:task).permit(:content, :deadline, :status, :priority, {:label_ids => []})
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user,{only:[:edit,:update]}

  def ensure_correct_user
    if @current_user.id != params[:id].to_i
      flash[:notice] = "You don't have authority"
      redirect_to("/")
    end
  end
  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks.page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render "edit"
    end
  end

  def login_form
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Login Successful"
      redirect_to("/")
    else
      @error_message = "The User does not exist"
      render "login_form"
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "Logout Completed"
    redirect_to("/")
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :admin)
    end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>Edit User</h2>



<%= form_for @user, url:admin_user_path(@user) do |f| %>
<p>
  Name<br>
  <%= f.text_field :name %>
  <%= @user.errors.messages[:name][0]%>
</p>
<p>
  Email<br>
  <%= f.text_field :email %>
  <%= @user.errors.messages[:email][0]%>
</p>
<p>
  Password<br>
  <%= f.password_field :password %>
  <%= @user.errors.messages[:password][0]%>
</p>
<p>
  Admin Authority :
  <%= f.check_box(:admin, {}, :true, :false)%>
</p>

<p>
  <%= f.submit  %>
</p>

<%end%>

app/views/admin/users/index.html.erb
<h1>User Index #admin</h1>
<p>
<%= link_to "Add New User", new_admin_user_path %>
</p>

<div><ul>
  <% @users.each do |user| %>
    <div><li>
      <%= link_to user.name, admin_user_path(user) %>
      <%= link_to "[Edit]", edit_admin_user_path(user)%>
      <%= link_to "[Delete]", admin_user_path(user), method: :delete, data: {confirm: "Sure?"} %>
    </li></div>
  <% end %>
</ul></div>
</table>

app/views/admin/users/new.html.erb
<h2>New User</h2>



<%= form_for :user, url:admin_users_path do |f| %>
<p>
  Name<br>
  <%= f.text_field :name %>
  <%= @user.errors.messages[:name][0]%>
</p>
<p>
  Email<br>
  <%= f.text_field :email %>
  <%= @user.errors.messages[:email][0]%>
</p>
<p>
  Password<br>
  <%= f.password_field :password %>
  <%= @user.errors.messages[:password][0]%>
</p>
<p>
  Admin Authority : 
  <%= f.check_box(:admin, {}, :true, :false)%>
</p>

<p>
  <%= f.submit  %>
</p>

<%end%>

app/views/admin/users/show.html.erb
<h2><%= @user.name %></h2>

<div>
<%= "#{@user.name}'s all tasks"%>
</div>

<table class="table table-bordered table-hover">
  <tr>
    <th>Content</th>
    <th><a href="/?sort=status" class="btn">Status</a></th>
    <th><a href="/?sort=priority" class="btn">Priority</a></th>
    <th><a href="/?sort=deadline" class="btn">Deadline</a></th>
    <th><a href="/?sort=updated_at" class="btn">Update</a></th>
    <th></th>
  </tr>
  <% @user.tasks.each do |task| %>
  <tr>
    <td><%=task.content%></td>
    <td><%=task.status%></td>
    <td><%=task.priority%></td>
    <td><%=task.deadline%></td>
    <td><%=task.updated_at%></td>
    <td><%= link_to "[Edit]", edit_task_path(task)  %>
        <%= link_to "[Delete]", task_path(task), method: :delete, data: {confirm: "Sure?"} %></td>
  </tr>
  <% end %>
</table>

app/views/labels/index.html.erb
<h2>ALL Labels</h2>
<div>
  <% @labels.each do |label| %>
    <%= link_to label.name, label_path(label) %>
    <%= link_to "[x]", label_path(label), method: :delete, data: {confirm: "Sure?"} %>
  <%end%>
</div>


<div>Add New Label
<%=form_for :label, url:labels_path do |f| %>
<p>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.submit  %>
</p>
<%end%>

<div>

app/views/labels/show.html.erb
<h2><%= @label.name %></h2>

<table class="table table-bordered table-hover">
  <tr>
    <th>User</th>
    <th>Content</th>
    <th>Labels</th>
    <th><a href="/?sort=status" class="btn">Status</a></th>
    <th><a href="/?sort=priority" class="btn">Priority</a></th>
    <th><a href="/?sort=deadline" class="btn">Deadline</a></th>
    <th><a href="/?sort=updated_at" class="btn">Update</a></th>
    <th></th>
  </tr>
  <% @tasks.each do |task| %>
  <tr>
    <td><%=link_to(task.user.name, "/users/#{task.user.id}") %></td>
    <td><%=task.content%></td>
    <td><%task.labels.each do |label|%>
          <%=label.name%>
        <%end%>
    </td>
    <td><%=task.status%></td>
    <td><%=task.priority%></td>
    <td><%=task.deadline%></td>
    <td><%=task.updated_at%></td>
    <td><%= link_to "[Edit]", edit_task_path(task)  %>
        <%= link_to "[Delete]", task_path(task), method: :delete, data: {confirm: "Sure?"} %></td>
  </tr>
  <% end %>
</table>
<%= paginate @tasks %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-inverse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Top", "/" %></li>
        
        <li><%= link_to "Add Task", new_task_path %></li>
        <li><%= link_to "Label", labels_path %></li>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <% if @current_user %>
          <li><%= link_to "Admin", admin_users_path %></li>
          <li><%= link_to(@current_user.name, "/users/#{@current_user.id}") %></li>
          <li><%= link_to "Logout", logout_path, method: :post %></li>
        <%else%>
          <li><%= link_to "Login", login_path %></li>
        <%end%>
      </ul>
    </nav>


    <% if flash[:notice] %>
      <div>
        <%= flash[:notice] %>
      </div>
    <%end%>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>

<%= form_for @task, url:task_path do |f| %>
<p>
<% @task.errors.full_messages.each do |message| %>
  <%= message %>
<%end%>
</p>
<p>
  Content<br>
  <%= f.text_area :content %>
</p>
<p>
  <%= f.label :Label %><br />
  <%= collection_check_boxes(:task, :label_ids, Label.all, :id, :name) do |b| %>
    <%= b.label { b.check_box + b.text } %>
  <% end %>
</p>
<p>
  Deadline<br>
  <%= f.date_field :deadline %>
</p>
<p>
  Status
  <%= f.select :status, Task.statuses.keys %>
</p>
<p>
  Priority
  <%= f.select :priority, Task.priorities.keys %>
</p>
<p>
  <%= f.submit  %>
</p>

<%end%>

app/views/tasks/index.html.erb
<h1>Task Index</h1>
<p>
<%= form_tag("/", method:"get") do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
<%end%>
</p>

<table class="table table-bordered table-hover">
  <tr>
    <th>User</th>
    <th>Content</th>
    <th>Labels</th>
    <th><%=link_to "Status", "/?sort=status" %></th>
    <!-- <th><a href="/?sort=status" class="btn">Status</a></th> -->
    <th><a href="/?sort=priority" class="btn">Priority</a></th>
    <th><a href="/?sort=deadline" class="btn">Deadline</a></th>
    <th><a href="/?sort=updated_at" class="btn">Update</a></th>
    <th></th>
  </tr>
  <% @tasks.each do |task| %>

  <tr>
    <td><%=link_to(task.user.name, "/users/#{task.user.id}") %></td>
    <td><%=task.content%></td>
    <td><%task.labels.each do |label|%>
          <%=label.name%>
        <%end%>
    </td>
    <td><%=task.status%></td>
    <td><%=task.priority%></td>
    <td><%=task.deadline%></td>
    <td><%=task.updated_at%></td>
    <td><%= link_to "[Edit]", edit_task_path(task)  %>
        <%= link_to "[Delete]", task_path(task), method: :delete, data: {confirm: "Sure?"} %></td>
  </tr>
  <% end %>
</table>
<%= paginate @tasks %>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= form_for :task, url:tasks_path do |f| %>
<p>
<% @task.errors.full_messages.each do |message| %>
  <%= message %>
<%end%>
</p>
<p>
  Content<br>
  <%= f.text_area :content %>
</p>
<p>
  <%= f.label :Label %><br />
  <%= collection_check_boxes(:task, :label_ids, Label.all, :id, :name) do |b| %>
    <%= b.label { b.check_box + b.text } %>
  <% end %>
</p>
<p>
  Deadline<br>
  <%= f.date_field :deadline %>
</p>
<p>
  Status
  <%= f.select :status, Task.statuses.keys %>
</p>
<p>
  Priority
  <%= f.select :priority, Task.priorities.keys %>
</p>
<p>
  <%= f.submit  %>
</p>

<%end%>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for @user, url:user_path(@user) do |f| %>
<p>
  Name<br>
  <%= f.text_field :name %>
  <%= @user.errors.messages[:name][0]%>
</p>
<p>
  Email<br>
  <%= f.text_field :email %>
  <%= @user.errors.messages[:email][0]%>
</p>
<p>
  Password<br>
  <%= f.password_field :password %>
  <%= @user.errors.messages[:password][0]%>
</p>

<p>
  <%= f.submit  %>
</p>

<%end%>

app/views/users/login_form.html.erb
<h2>Login</h2>

<% if @error_message %>
  <div>
    <%= @error_message %>
  </div>
<% end %>

<%= form_tag login_path do  %>

<p>
  Email<br>
  <%= text_field_tag :email %>
</p>
<p>
  Password<br>
  <%= password_field_tag :password %>
</p>

<p>
  <%= submit_tag  value="Login" %>
</p>

<%end%>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>

<p>
<%= link_to "[Edit]", edit_user_path %>
</p>

<div>
<%= "#{@user.name}'s all tasks"%>
</div>

<table class="table table-bordered table-hover">
  <tr>
    <th>User</th>
    <th>Content</th>
    <th>Labels</th>
    <th><a href="/?sort=status" class="btn">Status</a></th>
    <th><a href="/?sort=priority" class="btn">Priority</a></th>
    <th><a href="/?sort=deadline" class="btn">Deadline</a></th>
    <th><a href="/?sort=updated_at" class="btn">Update</a></th>
    <th></th>
  </tr>
  <% @tasks.each do |task| %>
  <tr>
    <td><%=link_to(task.user.name, "/users/#{task.user.id}") %></td>
    <td><%=task.content%></td>
    <td><%task.labels.each do |label|%>
          <%=label.name%>
        <%end%>
    </td>
    <td><%=task.status%></td>
    <td><%=task.priority%></td>
    <td><%=task.deadline%></td>
    <td><%=task.updated_at%></td>
    <td><%= link_to "[Edit]", edit_task_path(task)  %>
        <%= link_to "[Delete]", task_path(task), method: :delete, data: {confirm: "Sure?"} %></td>
  </tr>
  <% end %>
</table>
<%= paginate @tasks %>